export const FETCH_PLANETS = 'PLANETS:FETCH_ITEMS';
export const REMOVE_PLANET = 'PLANETS:REMOVE_ITEM';
export const FETCH_PLANETS_NEXT_PAGE = 'PLANETS:FECH_NEXT_PAGE';

export const FETCH_FILMS = 'FILMS:FETCH_ITEMS';
export const FETCH_FILMS_NEXT_PAGE = 'FILMS:FECH_NEXT_PAGE';

export const FETCH_STARSHIPS = 'STARSHIPS:FETCH_ITEMS';
export const FETCH_STARSHIPS_NEXT_PAGE = 'STARSHIPS:FECH_NEXT_PAGE';

export const FETCH_PEOPLE = 'PEOPLE:FETCH_ITEMS';
export const FETCH_PEOPLE_NEXT_PAGE = 'PEOPLE:FECH_NEXT_PAGE';

export const FETCH_SPECIES = 'SPECIES:FETCH_ITEMS';
export const FETCH_SPECIES_NEXT_PAGE = 'SPECIES:FECH_NEXT_PAGE';

export const FETCH_VEHICLES = 'VEHICLES:FETCH_ITEMS';
export const FETCH_VEHICLES_NEXT_PAGE = 'VEHICLES:FECH_NEXT_PAGE';

export const START_FETCHING = 'APP:START_FETCHING_STARWARS_DATA';
export const END_FETCHING = 'APP:END_FETCHING_STARWARS_DATA';