export const FETCH_PLANETS = 'PLANETS:FETCH_ITEMS';
export const REMOVE_PLANET = 'PLANETS:REMOVE_ITEM';

export const FETCH_FILMS = 'FILMS:FETCH_ITEMS';

export const FETCH_STARSHIPS = 'STARSHIPS:FETCH_ITEMS';

export const FETCH_PEOPLE = 'PEOPLE:FETCH_ITEMS';