export const FETCH_PLANETS = 'PLANETS:FETCH_ITEMS';
export const REMOVE_PLANET = 'PLANETS:REMOVE_ITEM';
export const FETCH_PLANETS_NEXT_PAGE = 'PLANETS:FETCH_NEXT_PAGE';
export const CREATE_PLANET = 'PLANETS:CREATE_ITEM';
export const EDIT_PLANET = 'PLANETS:EDIT_ITEM';

export const FETCH_FILMS = 'FILMS:FETCH_ITEMS';
export const FETCH_FILMS_NEXT_PAGE = 'FILMS:FETCH_NEXT_PAGE';

export const FETCH_STARSHIPS = 'STARSHIPS:FETCH_ITEMS';
export const FETCH_STARSHIPS_NEXT_PAGE = 'STARSHIPS:FETCH_NEXT_PAGE';

export const FETCH_PEOPLE = 'PEOPLE:FETCH_ITEMS';
export const FETCH_PEOPLE_NEXT_PAGE = 'PEOPLE:FETCH_NEXT_PAGE';

export const FETCH_SPECIES = 'SPECIES:FETCH_ITEMS';
export const FETCH_SPECIES_NEXT_PAGE = 'SPECIES:FETCH_NEXT_PAGE';

export const FETCH_VEHICLES = 'VEHICLES:FETCH_ITEMS';
export const FETCH_VEHICLES_NEXT_PAGE = 'VEHICLES:FETCH_NEXT_PAGE';

export const START_FETCHING = 'APP:START_FETCHING_STARWARS_DATA';
export const END_FETCHING = 'APP:END_FETCHING_STARWARS_DATA';